export default function HomePage() {
  return (
    <main className="landing-page">
      <nav className="topbar landing-nav"><a href="/">JobSearch</a><div className="nav-links"><a href="#how-it-works">How it works</a><a href="#features">Features</a><a className="open-source-link" href="https://github.com/subraatakumar/job-search">Open source</a><a className="nav-cta" href="/dashboard">Sign in</a></div></nav>
      <section className="hero-section">
        <div className="hero-copy"><div className="eyebrow">AI-assisted international job search</div><h1>Turn your next opportunity into a clear plan.</h1><p>Find roles in the countries you care about, understand visa sponsorship signals, create tailored applications, and prepare with confidence.</p><div className="hero-actions"><a className="primary-button" href="/profile">Create your profile <span>→</span></a><a className="text-link" href="#how-it-works">Explore how it works</a></div><div className="trust-line"><span>✓</span> Your profile stays under your control</div><div className="provider-line">Use your own AI provider — Ollama, OpenAI, or any compatible endpoint.</div></div>
        <div className="hero-art"><img src="/images/jobsearch-hero.png" alt="Professional using an AI-assisted international job search workspace" /></div>
      </section>
      <section className="intro-strip"><p><strong>One workspace for the journey from discovery to interview.</strong> JobSearch keeps your goals, documents, preparation, and application progress connected.</p></section>
      <section id="features" className="landing-section"><div className="section-label">What you can do</div><h2>Less searching. More intentional progress.</h2><div className="feature-grid"><article className="feature-card"><div className="feature-icon">⌕</div><h3>Search globally</h3><p>Explore approved job sources, company career pages, and roles you import yourself.</p></article><article className="feature-card"><div className="feature-icon">✦</div><h3>Prepare with AI</h3><p>Use your preferred hosted or local OpenAI-compatible model to tailor resumes, letters, and interview practice.</p></article><article className="feature-card"><div className="feature-icon">↗</div><h3>Track what matters</h3><p>Keep applications, deadlines, contacts, follow-ups, and outcomes in one focused workspace.</p></article></div></section>
      <section id="how-it-works" className="landing-section workflow-section"><div><div className="section-label">How it works</div><h2>A calmer way to move from hope to action.</h2></div><div className="workflow-list"><div><span>01</span><p><strong>Build your profile.</strong><br />Upload a text-based resume or enter your experience manually. Review every extracted detail.</p></div><div><span>02</span><p><strong>Find the right roles.</strong><br />Set countries, locations, keywords, and sponsorship preferences. Save the opportunities that fit.</p></div><div><span>03</span><p><strong>Prepare and follow through.</strong><br />Create job-specific drafts, practice for interviews, and track every application stage.</p></div></div></section>
      <section className="closing-card"><div><div className="section-label">Built for your workflow</div><h2>Your data. Your model. Your decisions.</h2><p>Run JobSearch locally with Docker and connect Ollama, OpenAI, or another compatible endpoint. AI suggestions remain drafts until you review them.</p></div><a className="secondary-button" href="/profile">Build your profile →</a></section>
      <footer><span>JobSearch · Open-source AI-assisted career tooling</span><a href="https://github.com/subraatakumar/job-search">View the project on GitHub ↗</a></footer>
    </main>
  );
}
