import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
import { Pool } from "pg";
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
function key() { const value = process.env.PROVIDER_ENCRYPTION_KEY; if (!value || !/^[0-9a-f]{64}$/i.test(value)) throw new Error("PROVIDER_ENCRYPTION_KEY must be 32 random bytes encoded as 64 hex characters"); return Buffer.from(value, "hex"); }
function encrypt(value: string) { const iv=randomBytes(12); const cipher=createCipheriv("aes-256-gcm",key(),iv); const ciphertext=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]); return { ciphertext:ciphertext.toString("base64"), iv:iv.toString("base64"), tag:cipher.getAuthTag().toString("base64") }; }
export function decryptProviderKey(row:{api_key_ciphertext:string;api_key_iv:string;api_key_tag:string}) { const decipher=createDecipheriv("aes-256-gcm",key(),Buffer.from(row.api_key_iv,"base64")); decipher.setAuthTag(Buffer.from(row.api_key_tag,"base64")); return Buffer.concat([decipher.update(Buffer.from(row.api_key_ciphertext,"base64")),decipher.final()]).toString("utf8"); }
async function ensureTable(){await pool.query(`CREATE TABLE IF NOT EXISTS ai_providers (user_id TEXT PRIMARY KEY, provider TEXT NOT NULL, endpoint TEXT NOT NULL, model TEXT NOT NULL, api_key_ciphertext TEXT NOT NULL DEFAULT '', api_key_iv TEXT NOT NULL DEFAULT '', api_key_tag TEXT NOT NULL DEFAULT '', updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`)}
export async function getAiProvider(userId:string){await ensureTable();const result=await pool.query("SELECT user_id, provider, endpoint, model, (api_key_ciphertext <> '') AS has_api_key, updated_at FROM ai_providers WHERE user_id=$1",[userId]);return result.rows[0]??null}
export async function getAiProviderCredentials(userId:string){await ensureTable();const result=await pool.query("SELECT provider,endpoint,model,api_key_ciphertext,api_key_iv,api_key_tag FROM ai_providers WHERE user_id=$1",[userId]);const row=result.rows[0];if(!row)return null;return {provider:row.provider,endpoint:row.endpoint,model:row.model,apiKey:row.api_key_ciphertext?decryptProviderKey(row):""};}
export async function saveAiProvider(userId:string,input:{provider:string;endpoint:string;model:string;apiKey:string}){await ensureTable();const encrypted=input.apiKey?encrypt(input.apiKey):{ciphertext:"",iv:"",tag:""};const result=await pool.query(`INSERT INTO ai_providers (user_id,provider,endpoint,model,api_key_ciphertext,api_key_iv,api_key_tag) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(user_id) DO UPDATE SET provider=EXCLUDED.provider,endpoint=EXCLUDED.endpoint,model=EXCLUDED.model,api_key_ciphertext=CASE WHEN EXCLUDED.api_key_ciphertext='' THEN ai_providers.api_key_ciphertext ELSE EXCLUDED.api_key_ciphertext END,api_key_iv=CASE WHEN EXCLUDED.api_key_iv='' THEN ai_providers.api_key_iv ELSE EXCLUDED.api_key_iv END,api_key_tag=CASE WHEN EXCLUDED.api_key_tag='' THEN ai_providers.api_key_tag ELSE EXCLUDED.api_key_tag END,updated_at=NOW() RETURNING user_id,provider,endpoint,model,(api_key_ciphertext <> '') AS has_api_key,updated_at`,[userId,input.provider,input.endpoint,input.model,encrypted.ciphertext,encrypted.iv,encrypted.tag]);return result.rows[0]}
