import { Pool } from "pg";
const pool=new Pool({connectionString:process.env.DATABASE_URL});
export type JobSource={id?:string;name:string;sourceType:"public_url"|"official_api"|"manual_url";baseUrl:string;enabled:boolean;frequency:string;countryName?:string};
async function ensureTable(){await pool.query(`CREATE TABLE IF NOT EXISTS job_sources (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL, name TEXT NOT NULL, source_type TEXT NOT NULL, base_url TEXT NOT NULL, country_name TEXT, enabled BOOLEAN NOT NULL DEFAULT TRUE, check_frequency TEXT NOT NULL DEFAULT 'daily', last_checked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(user_id,base_url))`);await pool.query("ALTER TABLE job_sources ADD COLUMN IF NOT EXISTS country_name TEXT")}
export async function getJobSources(userId:string){await ensureTable();return (await pool.query("SELECT id,name,source_type,base_url,country_name,enabled,check_frequency,last_checked_at FROM job_sources WHERE user_id=$1 ORDER BY created_at DESC",[userId])).rows}
export async function addJobSource(userId:string,source:Omit<JobSource,"id">){await ensureTable();return (await pool.query(`INSERT INTO job_sources(user_id,name,source_type,base_url,country_name,enabled,check_frequency) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(user_id,base_url) DO UPDATE SET name=EXCLUDED.name,country_name=EXCLUDED.country_name,enabled=EXCLUDED.enabled,check_frequency=EXCLUDED.check_frequency RETURNING id,name,source_type,base_url,country_name,enabled,check_frequency`,[userId,source.name,source.sourceType,source.baseUrl,source.countryName??null,source.enabled,source.frequency])).rows[0]}
export async function deleteJobSource(userId:string,id:string){await ensureTable();await pool.query("DELETE FROM job_sources WHERE user_id=$1 AND id=$2",[userId,id])}
export async function getJobSource(userId:string,id:string){await ensureTable();return (await pool.query("SELECT id,name,base_url FROM job_sources WHERE user_id=$1 AND id=$2",[userId,id])).rows[0]??null}
export async function saveJobs(userId:string,sourceId:string,jobs:{title:string;url:string;company:string;location:string;description:string}[]){await pool.query(`CREATE TABLE IF NOT EXISTS jobs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL, source_id UUID NOT NULL REFERENCES job_sources(id) ON DELETE CASCADE, title TEXT NOT NULL, company TEXT NOT NULL DEFAULT '', location TEXT NOT NULL DEFAULT '', description TEXT NOT NULL DEFAULT '', source_url TEXT NOT NULL, content_hash TEXT NOT NULL, first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(user_id,source_url))`);for(const job of jobs)await pool.query(`INSERT INTO jobs(user_id,source_id,title,company,location,description,source_url,content_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(user_id,source_url) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description,last_seen_at=NOW()`,[userId,sourceId,job.title,job.company,job.location,job.description,job.url,job.title+job.url]) ;await pool.query("UPDATE job_sources SET last_checked_at=NOW() WHERE user_id=$1 AND id=$2",[userId,sourceId]);return jobs.length}
export async function getJobs(userId:string){await pool.query(`CREATE TABLE IF NOT EXISTS jobs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL, source_id UUID NOT NULL, title TEXT NOT NULL, company TEXT NOT NULL DEFAULT '', location TEXT NOT NULL DEFAULT '', description TEXT NOT NULL DEFAULT '', source_url TEXT NOT NULL, content_hash TEXT NOT NULL, first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(user_id,source_url))`);return (await pool.query("SELECT id,title,company,location,description,source_url,first_seen_at,last_seen_at FROM jobs WHERE user_id=$1 ORDER BY last_seen_at DESC",[userId])).rows}
