import { Pool } from "pg";
const pool=new Pool({connectionString:process.env.DATABASE_URL});
export type JobSource={id?:string;name:string;sourceType:"public_url"|"official_api"|"manual_url";baseUrl:string;enabled:boolean;frequency:string;countryName?:string};
async function ensureTable(){await pool.query(`CREATE TABLE IF NOT EXISTS job_sources (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL, name TEXT NOT NULL, source_type TEXT NOT NULL, base_url TEXT NOT NULL, country_name TEXT, enabled BOOLEAN NOT NULL DEFAULT TRUE, check_frequency TEXT NOT NULL DEFAULT 'daily', last_checked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(user_id,base_url))`);await pool.query("ALTER TABLE job_sources ADD COLUMN IF NOT EXISTS country_name TEXT")}
export async function getJobSources(userId:string){await ensureTable();return (await pool.query("SELECT id,name,source_type,base_url,country_name,enabled,check_frequency,last_checked_at FROM job_sources WHERE user_id=$1 ORDER BY created_at DESC",[userId])).rows}
export async function addJobSource(userId:string,source:Omit<JobSource,"id">){await ensureTable();return (await pool.query(`INSERT INTO job_sources(user_id,name,source_type,base_url,country_name,enabled,check_frequency) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(user_id,base_url) DO UPDATE SET name=EXCLUDED.name,country_name=EXCLUDED.country_name,enabled=EXCLUDED.enabled,check_frequency=EXCLUDED.check_frequency RETURNING id,name,source_type,base_url,country_name,enabled,check_frequency`,[userId,source.name,source.sourceType,source.baseUrl,source.countryName??null,source.enabled,source.frequency])).rows[0]}
export async function deleteJobSource(userId:string,id:string){await ensureTable();await pool.query("DELETE FROM job_sources WHERE user_id=$1 AND id=$2",[userId,id])}
export async function getJobSource(userId:string,id:string){await ensureTable();return (await pool.query("SELECT id,name,base_url FROM job_sources WHERE user_id=$1 AND id=$2",[userId,id])).rows[0]??null}
export async function saveJobs(userId:string,sourceId:string,jobs:{title:string;url:string;applyUrl?:string;company:string;location:string;description:string;source?:string;sourceType?:string;sourceName?:string;structuredJobData?:Record<string,unknown>;matchScore?:number;matchReasons?:string[]}[]){await pool.query(`CREATE TABLE IF NOT EXISTS jobs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL, source_id UUID NOT NULL REFERENCES job_sources(id) ON DELETE CASCADE, title TEXT NOT NULL, company TEXT NOT NULL DEFAULT '', location TEXT NOT NULL DEFAULT '', description TEXT NOT NULL DEFAULT '', source_url TEXT NOT NULL, content_hash TEXT NOT NULL, apply_url TEXT, canonical_url TEXT, source_type TEXT, source_name TEXT, verification_status TEXT NOT NULL DEFAULT 'verified', verification_reason TEXT, structured_job_data JSONB, discovered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_verified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), match_score INTEGER, match_reasons JSONB, first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(user_id,source_url))`);
    for(const column of ["apply_url TEXT","canonical_url TEXT","source_type TEXT","source_name TEXT","verification_status TEXT NOT NULL DEFAULT 'verified'","verification_reason TEXT","structured_job_data JSONB","discovered_at TIMESTAMPTZ NOT NULL DEFAULT NOW()","last_verified_at TIMESTAMPTZ NOT NULL DEFAULT NOW()","match_score INTEGER","match_reasons JSONB"]) await pool.query(`ALTER TABLE jobs ADD COLUMN IF NOT EXISTS ${column}`);
    for(const job of jobs) await pool.query(`INSERT INTO jobs(user_id,source_id,title,company,location,description,source_url,apply_url,canonical_url,source_type,source_name,structured_job_data,content_hash,match_score,match_reasons) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(user_id,source_url) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description,apply_url=EXCLUDED.apply_url,structured_job_data=EXCLUDED.structured_job_data,last_verified_at=NOW(),last_seen_at=NOW(),match_score=EXCLUDED.match_score,match_reasons=EXCLUDED.match_reasons`,[userId,sourceId,job.title,job.company,job.location,job.description,job.url,job.applyUrl??job.url,job.url,job.sourceType??"public_url",job.sourceName??job.source??"",job.structuredJobData?JSON.stringify(job.structuredJobData):null,job.title+job.url,job.matchScore??null,job.matchReasons?JSON.stringify(job.matchReasons):null]);
    await pool.query("UPDATE job_sources SET last_checked_at=NOW() WHERE user_id=$1 AND id=$2",[userId,sourceId]);return jobs.length}
export async function getJobs(userId:string){await pool.query(`CREATE TABLE IF NOT EXISTS jobs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id TEXT NOT NULL, source_id UUID NOT NULL, title TEXT NOT NULL, company TEXT NOT NULL DEFAULT '', location TEXT NOT NULL DEFAULT '', description TEXT NOT NULL DEFAULT '', source_url TEXT NOT NULL, content_hash TEXT NOT NULL, first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(user_id,source_url))`);for(const column of ["apply_url TEXT","canonical_url TEXT","source_type TEXT","source_name TEXT","verification_status TEXT NOT NULL DEFAULT 'verified'","verification_reason TEXT","structured_job_data JSONB","discovered_at TIMESTAMPTZ NOT NULL DEFAULT NOW()","last_verified_at TIMESTAMPTZ NOT NULL DEFAULT NOW()","match_score INTEGER","match_reasons JSONB"]) await pool.query(`ALTER TABLE jobs ADD COLUMN IF NOT EXISTS ${column}`);return (await pool.query("SELECT id,title,company,location,description,source_url,apply_url,source_type,source_name,verification_status,verification_reason,discovered_at,last_verified_at,match_score,match_reasons,first_seen_at,last_seen_at FROM jobs WHERE user_id=$1 ORDER BY last_seen_at DESC",[userId])).rows}
export async function saveUserJob(userId:string,job:{title:string;company:string;location:string;description:string;sourceUrl:string;applyUrl?:string;sourceName?:string}){await pool.query(`CREATE TABLE IF NOT EXISTS saved_jobs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id TEXT NOT NULL,title TEXT NOT NULL,company TEXT NOT NULL DEFAULT '',location TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',source_url TEXT NOT NULL,apply_url TEXT,source_name TEXT,saved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,source_url))`);return (await pool.query(`INSERT INTO saved_jobs(user_id,title,company,location,description,source_url,apply_url,source_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(user_id,source_url) DO UPDATE SET apply_url=EXCLUDED.apply_url,source_name=EXCLUDED.source_name RETURNING id,saved_at`,[userId,job.title,job.company,job.location,job.description,job.sourceUrl,job.applyUrl??job.sourceUrl,job.sourceName??null])).rows[0]}
export async function recordSearch(userId:string,query:string,resultCount:number){await pool.query(`CREATE TABLE IF NOT EXISTS search_history (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id TEXT NOT NULL,query TEXT NOT NULL,result_count INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await pool.query("INSERT INTO search_history(user_id,query,result_count) VALUES($1,$2,$3)",[userId,query,resultCount])}
