"use client";
import {FormEvent, useState} from "react";
type Source={id:string;name:string;base_url:string;country_name?:string|null};
type Job={id:string;title:string;company:string;location:string;description:string;source_url:string;first_seen_at:string};
type Message={role:"user"|"assistant";text:string}; type Search={id:string;query:string;count:number};
export default function JobSearchWorkspace({firstName,email,sources,jobs}:{firstName:string;email:string;sources:Source[];jobs:Job[]}){
 const initial="Senior React Native roles in Germany"; const [query,setQuery]=useState(initial); const [activeQuery,setActiveQuery]=useState(initial); const [messages,setMessages]=useState<Message[]>([{role:"assistant",text:"Tell me what role you want to find. I’ll search your saved public sources and keep the results here."}]); const [history,setHistory]=useState<Search[]>([]); const [busy,setBusy]=useState<string|null>(null);
 async function search(event?:FormEvent,sourceId?:string){event?.preventDefault();const requested=sourceId?sources.find(s=>s.id===sourceId)?.name??sourceId:query.trim();if(!requested||busy)return;setBusy(sourceId??"search");setActiveQuery(requested);setMessages(m=>[...m,{role:"user",text:requested},{role:"assistant",text:"Searching your saved public sources…"}]);const targets=sourceId?[sourceId]:sources.map(s=>s.id);try{const results=await Promise.all(targets.map(id=>fetch(`/api/job-sources/${id}/refresh`,{method:"POST"}).then(async r=>({ok:r.ok,data:await r.json()}))));const count=results.reduce((sum,r)=>sum+(r.ok?Number(r.data.count??0):0),0);setHistory(h=>[{id:`${Date.now()}`,query:requested,count},...h.filter(x=>x.query!==requested)].slice(0,8));const text=count?`Found ${count} opportunity${count===1?"":"ies"}. Review the latest results below.`:"No matching opportunities were found in the saved sources yet.";setMessages(m=>[...m.slice(0,-1),{role:"assistant",text}]);}catch{setMessages(m=>[...m.slice(0,-1),{role:"assistant",text:"I couldn’t reach the search source. Please try again."}]);}finally{setBusy(null);}}
 function newSearch(){setQuery("");setActiveQuery("");setMessages([{role:"assistant",text:"What role, location, or sponsorship preference should I search for next?"}]);}
 function restore(item:Search){setQuery(item.query);setActiveQuery(item.query);setMessages([{role:"user",text:item.query},{role:"assistant",text:item.count?`This search found ${item.count} opportunity${item.count===1?"":"ies"}. You can run it again or refine it below.`:"This search did not find opportunities. You can refine it below."}]);}
 return <section className="job-search-workspace"><div className="search-workspace-shell"><aside className="search-history" aria-label="Search history"><div className="sidebar-identity"><div className="section-label">Your workspace</div><h1>Welcome back,<br/>{firstName}.</h1><p>Find roles that match your profile and preferences.</p><span className="account-chip">{email}</span></div><div className="history-heading"><strong>Search history</strong><button className="new-search-button" type="button" onClick={newSearch}>+ New search</button></div>{history.length?<div className="history-list">{history.map(item=><button className={`history-item ${item.query===activeQuery?"active":""}`} type="button" key={item.id} onClick={()=>restore(item)}><span>{item.query}</span><small>{item.count} found</small></button>)}</div>:<p className="history-empty">Your searches will appear here. Start with a role or location.</p>}</aside><div className="conversation-panel"><div className="conversation-header"><div><div className="section-label">Search assistant</div><h2>{activeQuery||"Start a new job search"}</h2></div><span className="assistant-status"><i/> Ready</span></div><div className="conversation-feed">{messages.map((message,index)=><div className={`message message-${message.role}`} key={`${message.role}-${index}`}><span className="message-label">{message.role==="user"?"You":"JobSearch"}</span><p>{message.text}</p></div>)}<div className="conversation-note">Searches currently run against your saved public sources. General web discovery can be connected to the Firecrawl search endpoint next.</div>{jobs.length>0&&<div className="inline-results"><strong>Latest opportunities</strong>{jobs.slice(0,6).map(job=><a href={job.source_url} target="_blank" rel="noreferrer" key={job.id}><span>{job.title}</span><small>{job.company}{job.location?` · ${job.location}`:""}</small></a>)}</div>}</div><form className="chat-composer" onSubmit={event=>search(event)}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Ask for a role, location, or visa preference…" aria-label="Job search query"/><button className="primary-button" type="submit" disabled={!sources.length||Boolean(busy)}>{busy==="search"?"Searching…":"Search jobs →"}</button></form><div className="quick-searches"><button type="button" onClick={()=>search()} disabled={!sources.length||Boolean(busy)}>Search my saved preferences</button>{sources.map(source=><button key={source.id} type="button" onClick={()=>search(undefined,source.id)} disabled={Boolean(busy)}>{source.name}</button>)}</div>{!sources.length&&<p className="muted">Add a public source to enable a search. Your conversation will remain available while you configure one.</p>}</div></div></section>;
}
